"""add fk indexes for query performance

Revision ID: 522e9275e257
Revises: ad5fbc05deea
Create Date: 2026-07-30 16:25:55.076281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522e9275e257'
down_revision: Union[str, Sequence[str], None] = 'ad5fbc05deea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_usage_log_document_id'), 'api_usage_log', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_rewrites_sentence_id'), 'rewrites', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_sentences_chunk_id'), 'sentences', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentences_chunk_id'), table_name='sentences')
    op.drop_index(op.f('ix_rewrites_sentence_id'), table_name='rewrites')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_index(op.f('ix_api_usage_log_document_id'), table_name='api_usage_log')
    # ### end Alembic commands ###
